# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely edit after that. If you find
# yourself editing this file very often, consider using Jekyll's data files
# feature for the data you need to update frequently.
#
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'bundle exec jekyll serve'. If you change this file, please restart the server process.

# Site settings
# These are used to personalize your new site. If you look in the HTML files,
# you will see them accessed via {{ site.title }}, {{ site.email }}, and so on.
# You can create any custom variable you would like, and they will be accessible
# in the templates via {{ site.myvariable }}.
title: Mahmoud Ilyan
email: mahmoudilyan@gmail.com
description: > # this means to ignore newlines until "baseurl:"
  Mahmoud Ilyan's Personal Site, Product's Case Studies, Book Notes & More
baseurl: "" # the subpath of your site, e.g. /blog
url: "" # the base hostname & protocol for your site, e.g. http://example.com
introduction: HI THERE, I’M MAHMOUD ILYAN! 
about: >
  Product Designer & Front-End Developer who loves turning complex problems into successful products, 
  always learning and always doing something new. See my <a href="/projects">Side projects </a> or my <a href="/case-studies">Work</a>
  <br><br>
  Worked for <br>
  <img src="/assets/images/clients-list.png" title="clients">
avatar: /assets/images/personal-pic.png 
twitter_url: https://twitter.com/mahmoudIlyan
github_url:  https://github.com/mahmoudilyan
dribbble_url: https://dribbble.com/mahmoudilyan
linkedin_url: https://www.linkedin.com/in/mahmoudilyan/
copyrights: > 
          Built with love using <a href="https://jekyllrb.com" target="_blank">Jekyll</a> 
          , <a href="http://bulma.io/" target="_blank">Bulma</a> 
          and powered by <a href="https://github.com/mahmoudilyan/mahmoudilyan.github.io" target="_blank">Github</a>
google_analytics: UA-107359695-1

# Build settings
markdown: kramdown
gems:
  - jekyll-feed
exclude:
  - Gemfile
  - Gemfile.lock

sass:
  sass_dir: assets
  style: compressed

environment: production  
